# configs/default.yaml

data:
  # paths to the input feature and label .npy files
  env_path: "data/env_data_normalized.npy"
  labels_path: "data/HURR_LOCS.npy"
  # sequence length (number of frames per sample)
  seq_len: 24
  # sliding‐window stride (defaults to seq_len // 2 if null)
  stride: 12

model:
  # input channels of the 3D‐conv stem
  in_channels: 19
  # hidden dimension for conv stem and transformer
  hidden_dim: 256
  # number of encoder/decoder layers
  num_layers: 6
  # number of attention heads
  num_heads: 8
  # number of object queries per frame
  num_queries: 15
  # spatial size (height and width) used in Timesformer stem
  img_size: 90

training:
  # batch size for training
  batch_size: 4
  # fraction of data used for validation
  val_split: 0.2
  # total training epochs
  epochs: 100
  # optimizer hyperparameters
  lr: 1e-4
  weight_decay: 1e-5
  # loss weights
  bbox_weight: 5.0
  cls_weight: 1.0
  noobj_coef: 0.1
  # OneCycleLR scheduler parameter
  pct_start: 0.1
  # random seed (null for no fixed seed)
  seed: null
  # device override: "cpu" or "cuda"
  device: "cuda"
  # where to save best checkpoint
  checkpoint_path: "model/best_model.pth"

visualization:
  # number of random segments to plot
  segments: 5
  # length (in frames) of each plotted segment
  seg_len: 10
  # objectness threshold for predictions
  score_thresh: 0.8
  # NMS radius in normalized coordinates
  nms_radius: 0.05
  # output directory for saved images
  output_dir: "vis_outputs"
